# This file is used entirely to contain all the libraries used at the beginning of the game to store the
# different possible hangman words for the user "choice" part.
import random
Pres = ["washington", "adams", "jefferson", "madison", "monroe", "quincyadams", "jackson", "vanburen", "harrison", "tyler", "polk", "taylor", "fillmore", "pierce", "buchanan", "lincoln", "johnson", "grant", "hayes", "garfield", "arthur", "cleveland", "harrison", "mckinley", "roosevelt", "taft", "wilson", "harding", "coolidge", "hoover", "roosevelt", "truman", "eisenhower", "kennedy", "johnson", "nixon", "ford", "carter", "reagan", "bush", "clinton", "bush", "obama", "trump", "biden"]
MLB = ["diamondbacks", "braves", "orioles", "redsox", "whitesox", "cubs", "reds", "guardians", "rockies", "tigers", "astros", "royals", "angels", "dodgers", "marlins", "brewers", "twins", "yankees", "mets", "athletics", "phillies", "pirates", "padres", "giants", "mariners", "cardinals", "rays", "rangers", "bluejays", "nationals"]
FF = ["mcdonalds", "wendys", "tacobell", "chipotle", "burgerKing", "kfc", "sonic", "pandaexpress", "chickfila", "qdoba", "sweetgreen", "wawa"]
Mam = ["bat", "bear", "bison", "camel", "cat", "cheetah", "chipmunk", "cow", "deer", "dog", "dolphin", "donkey", "elephant", "ferret", "fox", "giraffe", "goat", "gorilla", "hamster", "hare", "horse", "iguana", "jaguar", "kangaroo", "koala", "leopard", "lion", "lynx", "monkey", "moose", "mouse", "otter", "panda", "pig", "raccoon", "rabbit", "rat", "seal", "sheep", "skunk", "squirrel", "tiger", "wolf", "zebra", "antelope", "armadillo", "badger", "beaver", "cougar", "dolphin", "elephant", "elk", "gazelle", "grizzly", "hedgehog", "hippo", "hyena", "jaguarundi", "kitten", "lemur", "mole", "mongoose", "mule", "muskrat", "opossum", "orangutan", "puma", "reindeer", "rhinoceros", "seal", "sloth", "wombat", "yak"]
Moods = ["happy", "sad", "angry", "nostalgic", "melancholic", "pensive", "nostalgic", "joyful", "enthusiastic", "energetic", "excited", "elated", "relaxed", "content", "satisfied", "bored", "apathetic", "tired", "sleepy", "restless", "anxious", "stressed", "frustrated", "impatient", "irritable", ]
Shoes = ["nike", "adidas", "puma", "vans", "reebok", "asics", "timberland", "jordan", "sperry", "keds", "ugg", "converse", "clarks", "birkenstock", "crocs", "toms", "merrell", "hunter", "aldo", "sketchers", "newbalance"]
Dict = ["tiny","spend","tape","planned","whistle","oil","birds","go","serious","beside","private","children","pale","afraid","famous","solar","different","married","environment","wherever","tone","replace","leaving","necessary","adjective","mission","chair","ordinary","prize","flat","quite","minute","sudden","with","well","wealth","queen","dirty","bush","score","had","exact","tin","experience","fog","pony","simply","combination","almost","writing"
"fun","president","atmosphere","regular","instance","feature","out","experiment","took","carried","combination","thou","manufacturing","advice","telephone","game","nor","gray","vapor","brain","bark","shade","corn","famous","invented","real","torn","sister","fell","clean","case","double","story","straw","band","speech","difficult","spin","suggest","would","went","till","white","mainly","help","pipe","wing","field","drop","fought"
"leaf","village","evening","count","discuss","cannot","cell","managed","should","eleven","twelve","particular","reason","engineer","different","tall","saw","five","was","explain","salmon","combination","market","location","ring","structure","tin","fastened","degree","folks","aid","slope","terrible","mainly","principle","slide","temperature","sort","typical","mix","behind","spoken","public","town","protection","two","consist","put","evening","railroad"
"mud","seen","flame","universe","steep","steady","learn","know","said","want","stretch","improve","alive","desk","home","be","pressure","was","human","cookies","tongue","tight","story","by","settle","personal","getting","being","hurried","trip","live","additional","alone","decide","dried","refused","living","garden","crop","wolf","aid","bend","mind","cry","show","triangle","complete","laugh","cause","twice"
"so","horn","to","drove","identity","wind","area","flower","believed","wheel","weak","fish","early","particularly","complete","rice","chair","mean","shake","citizen","engineer","actual","upward","even","wealth","camp","breakfast","rich","center","bent","flower","safe","control","inch","chose","impossible","basis","composed","avoid","chief","plain","end","chain","excitement","seldom","matter","fifty","measure","new","football"
"available","atomic","feet","imagine","coffee","shore","close","highest","although","lady","library","exclaimed","between","knowledge","burst","situation","rapidly","sad","certainly","tall","bicycle","group","pretty","instant","camera","society","brave","shake","fact","took","industry","standard","like","product","older","giving","chemical","produce","work","journey","refer","club","pond","discover","plan","stick","leg","wait","board","touch"
"so","herd","shut","orange","river","shop","meant","acres","angry","wife","shake","personal","him","result","through","add","using","shaking","none","cause","give","pig","shadow","day","wool","slipped","disappear","thousand","universe","measure","bone","moon","middle","noon","eat","won","community","son","fast","dull","upper","men","done","willing","forty","phrase","met","tail","wealth","birds"
"four","wild","sister","whatever","taught","composed","date","planning","camera","office","husband","sail","southern","total","growth","trick","thirty","apart","completely","outer","personal","more","out","palace","nine","lady","herd","alone","angry","perhaps","vowel","slipped","visitor","verb","section","fifth","running","direction","present","eye","shells","brother","paragraph","score","rocky","nearby","phrase","electricity","blood","triangle"
"probably","sing","sail","power","camp","basket","leave","sleep","till","captured","wherever","afternoon","sum","softly","hot","as","copy","four","previous","truck","youth","massage","breakfast","old","serious","would","ring","worth","something","fight","tired","exercise","image","afraid","service","red","invented","supply","boat","been","freedom","lesson","lower","bad","apartment","noun","each","meant","main","ship"
"discover","machine","because","away","rough","gulf","spider","worse","silver","worse","hard","rest","gulf","pain","oldest","aloud","course","won","her","zoo","earn","pine","blanket","lunch","orange","bean","toy","recognize","fat","forgot","cage","tongue","simply","goes","flower","drink","victory","plural","doctor","usually","live","gift","fort","hurried","column","reason","leaving","fear","shadow","driver"
"man","sun","mine","on","laugh","egg","older","feel","subject","fully","square","us","fuel","try","blow","family","pie","knife","four","experience","corner","young","imagine","fewer","symbol","uncle","huge","observe","kitchen","wonderful","operation","consider","floor","desk","back","tent","grown","black","there","show","weight","grass","fastened","cold","minute","tin","understanding","pocket","ready","pick"
"importance","sitting","fewer","settle","me","thy","having","level","clothing","farm","nuts","cage","stick","tent","officer","wide","headed","gave","daily","thick","image","comfortable","dear","pure","private","attack","one","compass","tape","closely","safe","act","name","keep","sure","left","low","excitement","floor","best","screen","route","plus","apart","bridge","pot","bat","regular","metal","price"
"wrote","rapidly","that","dinner","count","becoming","newspaper","alphabet","gate","seems","getting","chapter","belong","answer","creature","captured","daily","continued","bend","property","century","under","habit","serious","mother","national","say","hang","become","water","key","bank","available","author","lose","amount","customs","replace","wonder","crowd","soap","either","lesson","discuss","trap","afraid","needed","build","pond","leg"
"fast","rabbit","verb","honor","route","series","education","one","bear","organized","discovery","dull","furniture","guess","song","done","arrange","honor","central","want","please","dry","do","we","milk","finish","field","instant","tears","mean","library","complete","swimming","sitting","smell","thee","strip","member","replied","paint","policeman","regular","toward","ever","jump","graph","determine","grade","slight","whom"
"typical","certainly","treated","flag","tried","eager","newspaper","shout","fell","acres","fairly","rear","individual","regular","belt","dirt","laid","triangle","foot","did","vote","leaving","extra","announced","worker","production","death","town","sudden","fort","hole","kitchen","plates","space","further","bite","they","perfect","already","is","daily","house","toy","grow","sat","paragraph","tall","might","line","compass"
"course","climate","paper","taste","lead","foreign","shoe","year","meat","bean","trouble","us","factory","when","post","meal","ruler","has","parallel","edge","north","feathers","community","refer","ants","well","ruler","progress","molecular","circle","transportation","after","problem","produce","route","common","middle","mouse","company","purpose","pretty","making","took","give","than","author","pet","television","became","field"
"worker","coach","industry","week","orbit","dark","atom","composed","badly","beyond","lying","ring","cause","try","quite","whom","soon","badly","nature","shoot","whatever","spend","planned","final","younger","ready","prize","related","may","personal","sharp","yet","pattern","swept","fire","fence","rapidly","toward","labor","hurt","like","appearance","fill","beat","characteristic","independent","it","oxygen","original","grass"
"than","left","heard","hide","origin","important","done","hard","chemical","edge","lion","finish","man","dug","part","general","car","circle","valuable","active","public","certain","tall","scale","carry","iron","does","worth","important","bell","ever","equator","speak","properly","element","pocket","tell","we","represent","factory","shorter","from","native","fully","tomorrow","southern","finest","seat","substance","height"
"tried","writing","related","is","zoo","itself","indicate","this","clothes","far","beyond","tell","shells","entirely","explore","solar","farther","religious","sky","fewer","making","steel","want","being","adventure","purple","bottle","hold","information","beautiful","settle","tune","border","gradually","wait","choose","dear","around","laugh","private","chain","partly","discussion","believed","highest","symbol","score","want","talk","strong"
"possible","sharp","itself","thick","snow","wrote","break","pure","three","solid","classroom","breeze","label","with","announced","someone","weigh","ahead","statement","supply","pair","softly","plate","tried","bank","material","primitive","task","block","born","earlier","equipment","bag","stone","telephone","fill","whole","mark","are","remarkable","atom","ahead","coffee","three","grew","tired","glass","enjoy","replace","roar"
"tip","whistle","song","dug","gone","danger","except","say","leather","seeing","outside","knowledge","triangle","former","fire","trick","adjective","throat","early","method","buffalo","was","idea","general","built","watch","among","farm","three","tool","bat","point","yard","center","nothing","green","coal","live","death","during","chief","handle","involved","came","lost","uncle","anyway","rocket","heard","six"
"coast","been","her","throat","pound","field","melted","north","complete","slightly","neighborhood","during","pattern","visitor","throw","arrow","drew","careful","care","east","grown","hurry","yesterday","whom","rate","club","cry","musical","cost","area","practice","other","balance","birthday","home","involved","engineer","pattern","coach","coffee","nearer","wall","engineer","appearance","edge","its","minerals","quarter","warn","fish"
"later","cotton","gave","broke","bush","became","respect","shelter","solution","imagine","adjective","world","pleasant","able","collect","science","new","detail","light","bear","having","grew","pair","improve","dear","official","music","capital","coal","gently","model","garage","neighborhood","sent","avoid","closely","feature","stone","improve","rain","chose","flag","copper","make","cow","blanket","ill","product","origin","object"
"sleep","chapter","dance","pay","instead","courage","had","larger","somebody","life","neighborhood","factor","religious","buy","burn","hungry","oil","parts","was","silly","baseball","cage","particles","onlinetools","five","court","least","would","fact","close","wife","greatly","ready","yellow","double","thank","scared","union","exciting","stick","slip","route","check","tried","sky","thirty","dog","heart","shake","porch"
"entirely","roar","connected","kind","reason","partly","steep","loose","slide","eat","butter","planned","ahead","pay","river","valuable","clean","most","both","her","call","army","until","way","wise","struggle","mostly","everywhere","saw","environment","them","disappear","best","shine","proper","either","instead","yard","form","club","perfect","vast","since","replied","figure","day","least","having","pan","method"
"share","wherever","among","loud","death","if","try","myself","sweet","explore","expression","lovely","curious","voice","dear","queen","studying","green","vapor","note","well","half","rear","case","wash","buy","fifteen","neighborhood","nothing","worse","made","development","somehow","avoid","ever","rubber","desert","generally","pictured","worker","pool","girl","graph","valuable","bottle","doll","climb","island","spent","kind"
"title","read","forward","club","real","castle","trace","successful","against","pleasure","warn","easily","remain","twenty","battle","held","twice","thought","strike","fastened","handle","against","doubt","fly","airplane","baseball","slabs","chart","slowly","mixture","basic","brief","studying","birthday","hay","today","completely","park","simplest","system","stood","pleasant","lucky","yesterday","taught","tree","them","lake","moon","came"
"other","meat","just","manner","loss","finest","made","bat","pack","blank","sit","including","herd","complete","driver","found","safe","swept","possible","fireplace","seat","machine","operation","yes","hold","sun","cool","level","any","darkness","smaller","roof","such","mirror","badly","done","one","growth","burst","facing","exchange","degree","larger","in","rice","husband","seldom","various","speak","ocean"
"making","whatever","faster","drawn","twelve","running","left","original","ancient","note","sport","dear","truck","doll","ready","onto","aside","high","smaller","receive","pictured","member","tree","buffalo","fruit","dot","answer","cream","monkey","captured","solve","circle","whale","mail","observe","empty","arrangement","choice","needed","later","sense","diagram","husband","seems","fast","pan","sat","numeral","movie","below"
"except","final","numeral","inside","time","studying","doll","substance","mill","at","wolf","joy","or","finally","beat","wood","chamber","hair","pie","product","cold","shown","duty","use","daily","blew","equally","finish","been","through","that","breakfast","hour","empty","making","nails","busy","symbol","determine","stronger","dot","wait","put","machinery","introduced","great","life","human","automobile","frighten"
"harbor","plus","within","loss","hurry","science","own","each","count","chicken","image","independent","hungry","rising","package","want","torn","hope","begun","being","join","concerned","ear","location","using","model","take","slowly","bicycle","out","breakfast","citizen","till","job","never","fruit","daughter","brain","shoulder","fish","larger","different","machine","pole","account","boat","simplest","was","choose","success"
"breeze","mission","supply","ancient","knew","truth","fully","shot","came","fell","generally","case","screen","share","made","shoulder","doing","gain","finish","learn","or","farm","skin","rubber","do","show","route","couple","immediately","tomorrow","everyone","lesson","want","news","trap","welcome","climb","move","father","correct","pair","studying","stepped","or","chart","driven","strike","hardly","cry","pot"
"hung","shall","phrase","nervous","dust","ring","shop","till","until","written","explain","office","from","writer","brave","simplest","dance","depth","follow","person","tongue","chose","show","wash","smaller","powder","ship","hand","getting","parts","will","verb","piano","drive","cream","ever","cat","grown","return","tonight","saved","chain","belt","read","aside","cook","within","gulf","provide","whole"
"roof","sudden","detail","blow","function","sets","heart","first","grow","private","gone","itself","instant","object","take","you","help","till","seems","situation","drive","that","sets","throat","dug","cook","torn","win","fish","unusual","hurt","recently","imagine","condition","entire","either","body","consist","iron","stood","brown","wool","up","income","finish","single","tongue","problem","expect","light"
"buffalo","anyway","battle","smallest","importance","kitchen","real","gone","low","box","yellow","notice","eager","yard","therefore","breath","tea","giving","diameter","tax","dinner","arrange","satellites","heavy","us","frighten","try","where","rice","cat","hit","peace","policeman","satellites","row","rush","history","neighbor","happen","inch","wonderful","breeze","selection","married","bad","told","round","soft","morning","share"
"lower","settle","goes","in","interest","show","scared","dust","another","frog","sang","though","improve","dinner","land","proper","stand","riding","highest","street","leaving","taught","personal","freedom","familiar","improve","college","loose","bark","into","hand","compare","interior","they","source","clearly","waste","smaller","glass","meat","another","try","went","detail","nearby","stranger","simple","busy","check","four"
"experiment","settle","getting","tomorrow","anything","tea","balance","came","view","victory","meet","outer","tomorrow","then","our","everybody","fur","check","not","spin","obtain","statement","however","acres","jungle","period","television","parts","job","cloth","lack","continent","roof","story","observe","want","captured","neighborhood","became","you","further","pencil","air","dear","lead","active","beat","maybe","industry","laid"
"usually","fear","say","friend","verb","card","medicine","judge","express","pleasure","noun","shine","rear","fact","afraid","which","island","double","coming","equal","rose","roll","ice","strike","six","pictured","children","using","different","horse","newspaper","like","several","unhappy","current","outer","fierce","fish","nearly","forward","thus","lungs","shoe","sink","running","of","author","frog","understanding","advice"
"mean","cage","beautiful","dish","prize","moment","orange","song","half","band","student","bee","whatever","safety","cell","underline","on","composition","pet","memory","somebody","voice","grandmother","cool","wet","value","tonight","lift","personal","recently","gone","curious","motion","crack","joined","look","cell","understanding","silly","engineer","rabbit","save","equipment","salmon","fourth","voice","bit","dug","company","lovely"
"sell","war","inch","give","acres","course","it","feed","quick","particles","command","salt","simplest","blood","law","height","till","men","him","family","writer","soil","generally","weight","apart","word","poor","compound","origin","basis","curious","chicken","draw","meet","sugar","badly","ranch","blow","greatly","factory","main","any","cause","doubt","surface","her","afraid","blank","among","your"
"able","condition","pole","closer","triangle","win","pull","pot","everyone","shorter","cell","product","crack","railroad","eaten","expression","smaller","musical","again","contain","produce","play","break","model","supply","team","picture","zoo","rubber","yourself","gain","children","fast","brain","chart","accident","sun","forty","chemical","whenever","sudden","headed","suit","situation","story","green","sure","trunk","upper","ruler"
"massage","up","transportation","represent","essential","sign","improve","natural","best","hung","slide","train","throat","rose","shade","morning","fastened","shoe","closely","frame","thee","shall","glass","us","properly","felt","youth","attempt","physical","replied","valley","vowel","out","cell","exchange","capital","action","easy","remarkable","chapter","jack","stiff","melted","property","completely","ago","climate","country","sunlight","bow"
"cool","surface","frighten","apple","seed","allow","clean","musical","were","grew","trap","lady","one","cause","surrounded","goose","huge","original","nearest","carefully","line","wool","box","earlier","together","merely","although","slept","poet","usual","chest","negative","affect","post","stream","buried","storm","brush","wood","itself","trouble","quickly","tool","construction","walk","have","house","disappear","policeman","crew"
"cowboy","claws","basic","treated","receive","upward","shinning","dear","religious","market","truck","silly","green","desk","below","brother","along","garden","plates","toy","twice","bad","shine","opinion","plural","feed","product","minute","stepped","forgot","radio","too","character","price","silly","mail","layers","nearer","courage","stuck","wear","labor","mathematics","plus","cowboy","spite","minute","cross","birthday","helpful"
"grade","buffalo","board","travel","naturally","more","son","pleasant","refused","affect","fish","statement","certainly","contain","thus","balance","pie","missing","hunter","bigger","entirely","older","moment","knew","southern","steep","canal","are","smaller","except","wind","problem","available","do","fear","great","clear","widely","forgot","cell","vast","beside","nice","place","term","read","tell","practical","happened","me"
"table","essential","sat","box","appearance","toward","rays","powerful","health","lot","term","street","noise","court","it","soil","flight","under","game","blow","about","basic","police","eventually","hurry","handle","today","count","brave","biggest","lovely","thin","spent","road","golden","travel","saw","generally","mountain","arm","moment","someone","regular","visit","past","simply","example","store","conversation","bag"
"service","information","corner","flow","machine","common","equipment","green","friendly","cookies","electric","accurate","income","pen","consider","seeing","follow","useful","receive","whether","mostly","discussion","equator","minute","own","eager","fifty","greatly","missing","transportation","which","aboard","system","date","sunlight","old","sand","fresh","snake","strong","edge","pocket","properly","hat","smallest","gun","hot","dish","gray","although"
"however","bread","milk","ever","excellent","found","movement","to","beside","upon","structure","face","bowl","queen","such","bar","his","depend","tide","meat","saw","couple","largest","those","pattern","string","particles","lead","dinner","correctly","riding","top","merely","provide","mixture","pond","easier","price","giving","mistake","corner","contain","attack","trick","born","gate","three","series","problem","industry"
"palace","state","does","correctly","location","bring","something","half","conversation","shore","equally","frame","sail","press","me","sudden","atmosphere","hospital","divide","chief","spent","bark","verb","herd","hot","curve","captured","member","fresh","water","city","football","fence","wheel","mine","syllable","setting","chosen","sat","low","flies","direction","carry","couple","very","star","when","common","airplane","jack"
"someone","train","stronger","park","before","pleasure","flies","structure","magic","old","prize","magic","forest","brain","tall","carry","highest","most","pleasant","load","heading","west","shut","author","extra","mouth","arrange","short","brief","health","primitive","pictured","full","fairly","knew","so","about","belt","question","plain","method","clean","smooth","tide","rise","movement","driven","coffee","buried","research"
"principal","half","curious","spell","colony","ill","short","feed","stepped","current","whose","daughter","wheel","couple","divide","breathing","swung","shelf","continent","coming","other","growth","forget","birth","salmon","grown","plate","please","wheel","poetry","dry","whenever","value","stiff","avoid","wear","distance","zoo","dish","whenever","dull","trap","younger","pour","consonant","answer","drive","upper","factor","stage"]










